config/routes.rb
Rails.application.routes.draw do

	mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
	mount Ckeditor::Engine => '/ckeditor'

	devise_for :users
	root 'welcome#index'

	resources :welcome, only: [:index]
	resources :activity, only: [:index, :show] do
		resources :city, only: [:index, :show]
	end
	resources :client, only: [:show]
	resources :region, only: [:index, :show]
	resources :city, only: [:show]
	resources :document, only: [:show]
	resources :contacts
	resources :excursions, only: [:show]
	resources :pages, only: [:show]

	namespace :v1 do
		resources :cities, only: [:index]
	end
end

app/models/region.rb
# == Schema Information
#
# Table name: regions
#
#  id                 :integer          not null, primary key
#  name               :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  description        :text
#  image_file_name    :string
#  image_content_type :string
#  image_file_size    :integer
#  image_updated_at   :datetime
#

class Region < ApplicationRecord
	validates :name, presence: true
	validates :name, length: { in: 4..30 }

	has_many :cities

	has_attached_file :image, styles: { large: "1000x565>", medium: "400x400>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/controllers/region_controller.rb
class RegionController < ApplicationController
	before_action :load_vars
	
	def index
    @regiones = Region.all
  end

	def show
		@region = Region.find(params[:id])
		@cities = City.where(region_id: params[:id])
	end
end

app/helpers/region_helper.rb
module RegionHelper
end

app/views/region/index.html.haml
.ui.breadcrumb
  = link_to "Inicio", root_path, {class: "section"}
  %i.right.chevron.icon.divider
  .active.section
    Regiones


%h2.ui.header
  .content 
    Regiones

.ui.grid.attached
  - @regiones.each do |region|
    .sixteen.wide.mobile.eight.wide.tablet.eight.wide.computer.column
      .ui.link.cards
        .ui.card.fluid
          %a.content{href: region_path(region.id)}
            %h3.ui.header
              = region.name
          %a.image{href: region_path(region.id)}
            = image_tag region.image.url(:medium)

app/views/region/show.html.haml
.ui.breadcrumb
	= link_to "Inicio", root_path, {class: "section"}
	%i.right.chevron.icon.divider
	= link_to "Regiones", region_index_path, {class: "section"}
	%i.right.chevron.icon.divider
	.active.section
		= @region.name

%h2.ui.header
	.content 
		= @region.name

- if @cities.any?
	.ui.grid.attached
		- @cities.each do |city|
			.sixteen.wide.mobile.eight.wide.tablet.five.wide.computer.column
				.ui.cards
					.ui.card.fluid
						.content
							%h3.ui.header
								= city.name
						.content
							- new_activity = 0
							- Client.where(city_id: city.id).order(:activity_id).each do |client|
								- if new_activity!=client.activity_id
									- new_activity=client.activity_id
									.ui.small.feed
										.event
											.content
												.summary
													= link_to client.activity.name, activity_city_path(client.activity, city)
- else
	= render partial: "shared/no-results"