config/routes.rb
Rails.application.routes.draw do

	mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
	mount Ckeditor::Engine => '/ckeditor'

	devise_for :users
	root 'welcome#index'

	resources :welcome, only: [:index]
	resources :activity, only: [:index, :show] do
		resources :city, only: [:index, :show]
	end
	resources :client, only: [:show]
	resources :region, only: [:index, :show]
	resources :city, only: [:show]
	resources :document, only: [:show]
	resources :contacts
	resources :excursions, only: [:show]
	resources :pages, only: [:show]

	namespace :v1 do
		resources :cities, only: [:index]
	end
end

app/views/shared/_activities-per-city.haml
-#- if @excursions.any?
-#  %a.fluid.ui.massive.ui.button.excursion-button{href: "javascript:;"}
-#    = "Excursiones"
-#
-#  .ui.hidden.divider
-#
-#- if @clients.any?
-#  .ui.styled.accordion
-#    - activities = @clients.map{|cl| cl.activity}.uniq
-#    - activities.each do |act|
-#      .title
-#        %i.dropdown.icon
-#        = "#{act.name} en #{@city.name}"
-#      .content
-#        - @clients.where(activity: act).each do |client|
-#          %p.transition.visible{style: "display: block !important;"}
-#            = link_to client.name, client_path(client)
-#
-#  .ui.hidden.divider
-#
-#- if @excursions.any?
-#  .ui.modal.fullscreen
-#    %i.close.icon
-#    .header
-#      = "Excursiones en #{@title}"
-#    .scrolling.content
-#      = render partial: "excursions", locals: {excursions: @excursions}
-#
-#  :javascript
-#    $("a.excursion-button").click(function(){
-#      $('.ui.fullscreen.modal').modal('show');
-#    });
-#
-#
-#:javascript
-#  $('.ui.accordion').accordion();

app/views/shared/_contact-client.html.haml
.description
	- if client.phone.present?
		%div
			%i.phone.volume.icon
			= client.phone
	- if client.email.present?
		%div
			%i.at.icon
			= client.email
	- if client.google_map.present?
		%div
			%i.map.marker.alternate.icon
			= client.google_map["formatted_address"]
	- if client.web.present?
		%div
			%i.globe.icon
			= client.web
	- if client.facebook.present?
		%div
			%i.facebook.icon
			= client.facebook

app/views/shared/_error-messages.html.haml
- if notice
  .ui.green.inverted.segment
    = raw notice

- if alert
  .ui.red.inverted.segment
    = raw alert

app/views/shared/_footer.html.erb
<div class='ui grid'>
  <div class='sixteen wide column'>
    <div class="ui inverted vertical footer segment">
      <div class="ui center aligned container">
        <%= image_tag "logo_blanco.png", {class: "ui centered small image"} %>
        <div class="ui horizontal inverted small divided link list">
          <a class="item" href="#">Contacto</a>
          <%= link_to "Términos y condiciones", document_path(2), class: "item" %>
          <%= link_to "Políticas de privacidad", document_path(1), class: "item" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_image-on-top.html.haml
- if image.present?
  .ui.grid.attached.gallery
    .sixteen.wide.computer.column{style: "background-image: url(#{asset_path image.url(:large)}); background-repeat: no-repeat; background-size: cover; background-position: center", data: {imageindex: "0"}}

  .ui.divider

app/views/shared/_left-banner.html.haml
- if banners.present?
  - banner_left = banners.where(location_left: true)
  - if banner_left.any?
    - banner_left.sample(3).each do |banner|
      .card.banner-card
        - if banner.image_left.exists?
          - banner.views = banner.views.to_i + 1
          - banner.save!
          - if banner.link.present?
            %a.image{href: "#{banner.link}", target: "_blank"}
              = image_tag banner.image_left.url(:normal), {class: ""}
          - else
            = image_tag banner.image_left.url(:normal), {class: ""}

app/views/shared/_left-side.html.haml
- unless controller_name == "welcome"
  .ui.fluid.vertical.text.menu
    %h3.ui.header Elegí una ciudad
    .ui.fluid.search
      .ui.icon.input
        %input.prompt{placeholder: "Buscar ciudade...", type: "text"}/
        %i.search.icon
      .results
    .ui.divider

- if controller_name == "welcome"
  .ui.grid
    .tablet.only.column.computer.only.column
      = render partial: "shared/left-banner", locals: {banners: @banners}
- elsif controller_name == "pages"
  .ui.grid
    .tablet.only.column.computer.only.column
      .ui.vertical.menu.inverted.fluid
        - if @pages_current_section.any?
          - @pages_current_section.each do |page|
            %a.item{href: page_path(page), :class => ("active" if page.id == params[:id].to_i)}
              = page.title
- elsif controller_name == "city"
  %h4.ui.header.blue
    = @city.name
  - if @categories.any?
    .ui.grid
      .tablet.only.column.computer.only.column
        .ui.vertical.menu.fluid
          - @categories.each do |category|
            .item
              %a.header{href: "?category=#{category.id}"}
                = category.title
              - if category.children.any?
                .menu
                  %a.item{href: "#"}
                    Mostrar todos
                  - category.children.each do |subcategory|
                    %a.item{href: "?category=#{category.id}&subcategory=#{subcategory.id}"}
                      = subcategory.title
- elsif controller_name == "client"
  = render partial: "shared/left-banner", locals: {banners: @banners}

app/views/shared/_no-results.html.haml
.ui.bottom.attached.warning.message
  %i.warning.icon
  UPS!!! Parece que por el momento no tenemos resultados.

app/views/shared/_regions-navigator.html.haml
.target-menu-popup
.ui.fluid.popup.transition.hidden
  .ui.equal.width.divided.grid
    - if regions
      - regions.each do |region|
        .column
          .ui.basic.segment
            %h4.ui.header= region.name
            %div
            %div= image_tag region.image.url(:medium), class: "ui fluid image"
            .ui.text.menu
              %a.desination.ui.green.button
                Elija una ciudad
              .ui.fluid.popup.transition.hidden.popup_destinations
                - region.cities.each do |city|
                  %a{href: "#{city_path(city.id)}"}
                    %i.angle.right.icon
                    = city.name
                  %br/

app/views/shared/_right-banner.html.haml
- if banners.present?
  - banner_right = banners.where(location_right: true)
  - if banner_right.any?
    - banner_right.sample(3).each do |banner|
      .card.banner-card
        - if banner.image_right.exists?
          - banner.views = banner.views.to_i + 1
          - banner.save!
          - if banner.link.present?
            %a.image{href: "#{banner.link}", target: "_blank"}
              = image_tag banner.image_right.url(:normal), {class: ""}
          - else
            = image_tag banner.image_right.url(:normal), {class: ""}