config/routes.rb
Rails.application.routes.draw do

	mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
	mount Ckeditor::Engine => '/ckeditor'

	devise_for :users
	root 'welcome#index'

	resources :welcome, only: [:index]
	resources :activity, only: [:index, :show] do
		resources :city, only: [:index, :show]
	end
	resources :client, only: [:show]
	resources :region, only: [:index, :show]
	resources :city, only: [:show]
	resources :document, only: [:show]
	resources :contacts
	resources :excursions, only: [:show]
	resources :pages, only: [:show]

	namespace :v1 do
		resources :cities, only: [:index]
	end
end

app/models/activity.rb
# == Schema Information
#
# Table name: activities
#
#  id                 :integer          not null, primary key
#  name               :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  image_file_name    :string
#  image_content_type :string
#  image_file_size    :integer
#  image_updated_at   :datetime
#  description        :string
#  html               :text
#  city_id            :integer
#

class Activity < ApplicationRecord
	acts_as_ordered_taggable

	validates :name, presence: true
	validates :name, length: { in: 2..200 }

	belongs_to :city
  has_many :clients
	belongs_to :section

	has_many :activity_pages
	has_many :pages, through: :activity_pages

	has_attached_file :image, styles: { large: "1000x565>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	def slug
		self.name.parameterize
	end
end

app/controllers/activity_controller.rb
class ActivityController < ApplicationController
	before_action :load_vars
	
	def index
		@activities = Activity.all
	end

	def show
		@activity = Activity.find(params[:id])
		@clients = Client.where(activity_id: params[:id])
    @cities = @activity.clients.map{|client| [client.city.id, client.city.name]}.uniq
	end
end

app/helpers/activity_helper.rb
module ActivityHelper
end

app/views/activity/index.html.haml
.ui.breadcrumb
	= link_to "Inicio", root_path, {class: "section"}
	%i.right.chevron.icon.divider
	.active.section
		Actividades


%h2.ui.header
	.content 
		Actividades

.ui.grid.attached
	- @activities.each do |activity|
		.sixteen.wide.mobile.eight.wide.tablet.eight.wide.computer.column
			.ui.link.cards
				.ui.card.fluid
					%a.content{href: activity_path(activity.id)}
						%h3.ui.header
							= activity.name
					%a.image{href: activity_path(activity.id)}
						= image_tag activity.image.url(:medium)

app/views/activity/show.html.haml
.ui.breadcrumb
	= link_to "Inicio", root_path, {class: "section"}
	%i.right.chevron.icon.divider
	= link_to "Actividades", activity_index_path, {class: "section"}
	%i.right.chevron.icon.divider
	.active.section
		= @activity.name


%h2.ui.header
	.content 
		= @activity.name
	%div
		.teal.large.ui.buttons.city-selection
			%button.ui.button{data: {city: 0}}
				Todas las ciudades
			- @cities.each do |city| 
				%button.ui.button{data: {city: city[0]}}
					= city[1]

- if @clients.any?
	.ui.grid.attached
		- @clients.each do |client|
			.sixteen.wide.mobile.eight.wide.tablet.eight.wide.computer.column.card-client{data: {city: client.city.id}}
				.ui.link.cards
					.ui.card.fluid
						%a.content{href: client_path(client.id)}
							%h3.ui.header
								= client.name
						%a.image{href: client_path(client.id)}
							= image_tag client.image.url(:medium)
						-#.extra
						-#	Rating:
						-#	.ui.star.rating{data:{rating: (0...5).to_a.sample, "max-rating": 5 }}
- else
	= render partial: "shared/no-results"

:javascript
	$(function(){
		$(".city-selection button").click(function(){
			$(".card-client").hide();
			city = $(this).data("city");
			console.log(city);
			$(".card-client").each(function(e){
				console.log($(this).data("city"), city);
				if(city == 0){
					$(".card-client").show();
				} else {
					if( $(this).data("city") == city ){
						$(this).show();
					}
				}
			})
		})
	})