config/routes.rb
Rails.application.routes.draw do

	mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
	mount Ckeditor::Engine => '/ckeditor'

	devise_for :users
	root 'welcome#index'

	resources :welcome, only: [:index]
	resources :activity, only: [:index, :show] do
		resources :city, only: [:index, :show]
	end
	resources :client, only: [:show]
	resources :region, only: [:index, :show]
	resources :city, only: [:show]
	resources :document, only: [:show]
	resources :contacts
	resources :excursions, only: [:show]
	resources :pages, only: [:show]

	namespace :v1 do
		resources :cities, only: [:index]
	end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Turismo
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{href: "https://fonts.googleapis.com/css?family=Roboto", rel: "stylesheet"}/
  %body
    .ui.fluid.container
      .ui.header-top
        .ui.grid.padded
          .sixteen.wide.column
            .ui.secondary.menu
              .header.item.logo
                %a{href: root_path}
                  = image_tag "logo-header.png", {class: "ui medium image"}
              .right.menu
                .ui.dropdown.icon.item.mobile.only.grid
                  %i.bars.icon
                  .menu
                    = link_to "Inicio", root_path, class: "item"
                    .item
                      %i.dropdown.icon
                      %span.text Encontrá tu destino
                      .menu
                        - if @regions.present?
                          - @regions.each do |region|
                            = link_to region[:name], region_path(region.id), class: "item"
                    = link_to "Contacto", new_contact_path, class: "ui item"
                = link_to "Inicio", root_path, class: "ui item tablet only computer only grid"
                .ui.text.menu.tablet.only.computer.only.grid
                  %a.browse.item
                    Encontrá tu destino
                = link_to "Contacto", new_contact_path, class: "ui item tablet only computer only grid #{controller_name == 'contacts' ? 'active' : ''}"
                - if user_signed_in?
                  .ui.dropdown.item.tablet.only.computer.only.grid
                    = current_user.name
                    %i.dropdown.icon
                    .menu.user-menu
                      = link_to "Datos personales", edit_user_registration_path, class: "ui item"
                      - if current_user.admin?
                        = link_to "Administrador", rails_admin.dashboard_path, class: "ui item", target: "_blank"
                      = link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "ui item"
                - else
                  = link_to "Ingresar", user_session_path, class: "ui item tablet only computer only grid #{controller_name == 'sessions' ? 'active' : ''}"

      = render partial: "shared/regions-navigator", locals: {regions: @regions}
      - if controller_name == "welcome"
        / Page Contents
        .pusher
          .ui.vertical.masthead.center.aligned.segment
            .left-side-menu-home
              .ui.vertical.menu.inverted.fluid
                - if @sections.any?
                  - @sections.each do |section|
                    %a.item{href: page_path(section.first_page)}
                      = section.title

            .ui.text.container
              %h1.ui.inverted.header
                Tan simple como escribir tu destino
              .ui.fluid.search
                .ui.icon.input.fluid
                  %input.prompt{placeholder: "Buscar ciudade...", type: "text"}/
                  %i.search.icon
                .results
          .ui.vertical.segment
            = banner_top_home @banners
          .ui.vertical.segment
            .ui.grid.padded
              .sixteen.wide.mobile.four.wide.tablet.three.wide.computer.column.left-menu
                = render partial: "shared/left-side"
              .sixteen.wide.mobile.twelve.wide.tablet.ten.wide.computer.column
                = yield
              .sixteen.wide.mobile.four.wide.tablet.three.wide.computer.column
                = render partial: "shared/right-banner", locals: {banners: @banners}
      - else
        .ui.grid.padded
          .sixteen.wide.mobile.sixteen.wide.tablet.sixteen.wide.computer.column
            .ui.grid.padded
              .sixteen.wide.mobile.four.wide.tablet.three.wide.computer.column.left-menu
                = render partial: "shared/left-side"
                - if controller_name == "city"
                  = render partial: "shared/activities-per-city"
                - if controller_name != "client"
                  .ui.link.cards
                    = render partial: "shared/left-banner", locals: {banners: @banners}
              - if controller_name == "client"
                .sixteen.wide.mobile.twelve.wide.tablet.thirteen.wide.computer.column
                  = yield
              - else
                .sixteen.wide.mobile.eight.wide.tablet.ten.wide.computer.column
                  = yield
                .four.wide.tablet.only.three.wide.computer.only.column
                  .ui.link.cards
                    = render partial: "shared/right-banner", locals: {banners: @banners}

      = render partial: "shared/footer"

:javascript
  $( document ).ready(function() {
    $('.ui.search').search({
      minCharacters : 3,
      searchFullText: false,
      apiSettings   : {
        onResponse: function(githubResponse) {
          console.log(githubResponse)
          var response = {
            results : []
          };
          // translate GitHub API response to work with search
          $.each(githubResponse, function(index, item) {
            // add result to category
            response.results.push({
              title       : item.name,
              description : item.region_name,
              url         : item.url
            });
          });
          console.log(response)
          return response;
        },
        url: "#{raw v1_cities_path}?query={query}"
      }
    });

    $('.rating').rating({
        initialRating: 2,
        maxRating: 4,
        onRate: function(value){
          console.log("ranked", value)
        }
    });
    $('.ui.dropdown').dropdown();

    $('.menu .browse').popup({
      inline   : true,
      hoverable: true,
      position : 'bottom center',
      popup: $('.ui.fluid.popup'),
      target: '.target-menu-popup',
      delay: {
        show: 300,
        hide: 800
        },
      on: 'click'
    });

    $('.desination').popup({
      hoverable: true,
      position : 'bottom left'
    });
  });